/**
 * Prepares the database for development:
 *   1. Applies the .sql files generated by drizzle-kit (creates the tables).
 *   2. Inserts sample players and next Wednesday's match.
 *
 * Usage:
 *   node scripts/seed.mjs                  # local databases only (file:...)
 *   node scripts/seed.mjs --yes            # allow writing to a remote database
 *   node scripts/seed.mjs --db=file:dev.db # force the target
 *   node scripts/seed.mjs --force          # seed even if players already exist
 *
 * Variable precedence: --db > .env.local > .env.
 */
import { createClient } from "@libsql/client";
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";

/* ------------------------------- env ------------------------------- */

/**
 * `process.loadEnvFile` does not override values that are already set, so
 * .env.local would never win over .env. Precedence is applied explicitly here.
 */
function loadEnvFile(file) {
  if (!existsSync(file)) return;

  for (const line of readFileSync(file, "utf8").split(/\r?\n/)) {
    const match = /^\s*([\w.-]+)\s*=\s*(.*)$/.exec(line);
    if (!match || line.trimStart().startsWith("#")) continue;

    const [, key, raw] = match;
    process.env[key] = raw.trim().replace(/^(['"])([\s\S]*)\1$/, "$2");
  }
}

for (const file of [".env", ".env.local"]) loadEnvFile(file);

const args = process.argv.slice(2);
const flag = (name) => args.includes(`--${name}`);
const option = (name) =>
  args.find((arg) => arg.startsWith(`--${name}=`))?.split("=").slice(1).join("=");

const url = option("db") ?? process.env.TURSO_DATABASE_URL;

if (!url) {
  console.error("TURSO_DATABASE_URL is missing. Copy .env.example to .env.local.");
  process.exit(1);
}

const isRemote = !url.startsWith("file:");

console.log(`Target: ${isRemote ? url.replace(/\/\/.*@/, "//") : url}`);

// Seeding sample data into a remote database is rarely what you want.
if (isRemote && !flag("yes")) {
  console.error("That is a remote database. Re-run with --yes if you really mean it.");
  process.exit(1);
}

const db = createClient({
  url,
  authToken: option("db") ? undefined : process.env.TURSO_AUTH_TOKEN,
});

/* ---------------------------- migrations ---------------------------- */

const migrationsDir = path.resolve("drizzle");
const files = readdirSync(migrationsDir)
  .filter((file) => file.endsWith(".sql"))
  .sort();

for (const file of files) {
  const sql = readFileSync(path.join(migrationsDir, file), "utf8");

  for (const statement of sql.split("--> statement-breakpoint")) {
    const trimmed = statement.trim();
    if (!trimmed) continue;

    try {
      await db.execute(trimmed);
    } catch (error) {
      if (!/already exists/i.test(String(error))) throw error;
    }
  }
}

console.log(`Schema applied (${files.length} migration file(s)).`);

/* ------------------------------- data ------------------------------- */

const existing = await db.execute("select count(*) as total from players");

if (Number(existing.rows[0].total) > 0 && !flag("force")) {
  console.log("Players already exist: nothing to seed. Use --force to add more.");
  process.exit(0);
}

const DEMO = [
  ["Diego", "Maradona", "dev"],
  ["Sophie", "Turner", "data"],
  ["Martin", "Reed", "marketing"],
  ["Camila", "Rojas", "it"],
  ["Ivan", "Salazar", "sales"],
  ["Valentina", "Cross", "design"],
  ["Bruno", "Hale", "product"],
  ["Lucy", "Harper", "finance"],
  ["Thomas", "Vega", "operations"],
  ["Anna", "Fields", "hr"],
  ["Joaquin", "Silva", "support"],
  ["Renata", "Poole", "management"],
];

const now = Date.now();

const players = DEMO.map(([firstName, lastName, area], index) => ({
  id: crypto.randomUUID(),
  firstName,
  lastName,
  area,
  createdAt: now + index,
}));

await db.batch(
  players.map((player) => ({
    sql: "insert into players (id, first_name, last_name, area, photo_url, photo_public_id, created_at) values (?, ?, ?, ?, null, null, ?)",
    args: [
      player.id,
      player.firstName,
      player.lastName,
      player.area,
      player.createdAt,
    ],
  })),
);

/** Next Wednesday at 19:00. */
const playedAt = (() => {
  const date = new Date();
  date.setHours(19, 0, 0, 0);
  const ahead = (3 - date.getDay() + 7) % 7;
  const passed = ahead === 0 && Date.now() > date.getTime();
  date.setDate(date.getDate() + (passed ? 7 : ahead));
  return date.getTime();
})();

const placeId = crypto.randomUUID();

await db.execute({
  sql: "insert into places (id, name, address, google_place_id, maps_url, lat, lng, created_at) values (?, ?, ?, null, ?, null, null, ?)",
  args: [
    placeId,
    "Pitch 3",
    "Av. Ejemplo 123",
    "https://www.google.com/maps/search/?api=1&query=Pitch+3",
    now,
  ],
});

const matchId = crypto.randomUUID();

// Seeded as a weekly fixture so the recurrence path has something to roll.
await db.execute({
  sql: "insert into matches (id, played_at, place_id, recurrence, series_id, created_at) values (?, ?, ?, 'weekly', ?, ?)",
  args: [matchId, playedAt, placeId, crypto.randomUUID(), now],
});

const lineup = players.slice(0, 10);

await db.batch(
  lineup.map((player, index) => ({
    sql: "insert into match_players (match_id, player_id, slot, created_at) values (?, ?, ?, ?)",
    args: [matchId, player.id, index, now + index],
  })),
);

console.log(
  `Done: ${players.length} players and 1 match (${lineup.length} on the pitch) on ${new Date(playedAt).toLocaleString("en-US")}.`,
);
