import { z } from "zod";
import { messages } from "@/i18n/server";

import { countLiveVisitors, forgetVisit, recordVisit } from "@/db/presence";
import { fail, json, readJson, route } from "@/lib/http";
import { getIsSuperAdmin } from "@/lib/session";

export const dynamic = "force-dynamic";

/**
 * The id is generated by the browser and means nothing on its own, so the
 * shape is all that is checked: it never identifies anybody.
 */
const beatSchema = z.object({
  id: z.string().regex(/^[A-Za-z0-9_-]{8,64}$/),
  /** Set by the beacon a closing tab fires. */
  leaving: z.boolean().optional(),
});

/** "Still here", or "gone". Sent by every open tab, guests included. */
export async function POST(request: Request) {
  return route(async () => {
    const { id, leaving } = await readJson(request, beatSchema);

    if (leaving) await forgetVisit(id);
    else await recordVisit(id);

    return json({ ok: true });
  });
}

/** The headcount. Super admin only. */
export async function GET() {
  return route(async () => {
    // The proxy already blocks this path, but the number never leaves the
    // server on the strength of a single guard.
    if (!(await getIsSuperAdmin())) {
      return fail((await messages()).superAdminOnly, 403);
    }

    return json({ count: await countLiveVisitors() });
  });
}
